--======================
-- VW_CUSTO_PRODUTO_DET
--======================

--VIEW DE DETALHAMENTO DO CUSTO DE PRODUÇÃO DE PRODUTOS

--TABELAS: MATERIAL, FICHA_TECNICA

CREATE OR REPLACE VIEW VW_CUSTO_PRODUTO_DET AS
    SELECT 
        A.COD_EMPRESA,
        A.COD_MAT,
        A.DESCRICAO,
        B.COD_MAT_NECES,
        C.DESCRICAO AS DESCRICAO_MAT_NECES,
        B.QTD_NECES,
        C.PRECO_UNIT,
        B.QTD_NECES*C.PRECO_UNIT CUSTO_NECES
    FROM MATERIAL A
        INNER JOIN FICHA_TECNICA B
        ON A.COD_MAT=B.COD_MAT_PROD
            AND A.COD_EMPRESA=B.COD_EMPRESA
        INNER JOIN MATERIAL C
        ON B.COD_MAT_NECES=C.COD_MAT
            AND A.COD_EMPRESA=C.COD_EMPRESA
    WHERE A.COD_TIP_MAT=2;


 --====================
-- TESTE
--=====================

SELECT * FROM VW_CUSTO_PRODUTO_DET
WHERE COD_EMPRESA=1
AND COD_MAT=1;
