--=========================
-- VW_CUSTO_PRODUTO_RESUMO
--=========================

--VIEW DE RESUMO DO CUSTO DE PRODUÇÃO DE PRODUTOS

--TABELAS: MATERIAL,FICHA_TECNICA

CREATE OR REPLACE VIEW VW_CUSTO_PRODUTO_RESUMO AS
    SELECT 
        A.COD_EMPRESA,
        A.COD_MAT,
        A.DESCRICAO,
        SUM(B.QTD_NECES*C.PRECO_UNIT) CUSTO,
        A.PRECO_UNIT PRECO_VENDA
    FROM MATERIAL A
        INNER JOIN FICHA_TECNICA B
        ON A.COD_MAT=B.COD_MAT_PROD
            AND A.COD_EMPRESA=B.COD_EMPRESA
        INNER JOIN MATERIAL C
        ON B.COD_MAT_NECES=C.COD_MAT
            AND A.COD_EMPRESA=C.COD_EMPRESA
    WHERE A.COD_TIP_MAT=2
    GROUP BY A.COD_EMPRESA,A.COD_MAT,A.DESCRICAO,A.PRECO_UNIT;
        

 --====================
-- TESTE
--=====================
    
SELECT * FROM VW_CUSTO_PRODUTO_RESUMO
WHERE COD_EMPRESA=1
--AND COD_MAT=1;
