-- =================================
-- PROCEDURE PRC_MOV_ESTOQUE
-- =================================

/*
REGRAS DE NEGÓCIO

VERIFICAR SE A OPERACAO E PERMITIDA 'E' (ENTRADA) E 'S' (SAIDA)
VERIFICAR SE O MATERIAL EXISTE

VERIFICOES DE SAIDA:

1 VERIFICAR SE O MATERIAL TEM SALDO NO ESTOQUE
2 VERIFICAR SE QTD SAIDA E MENOR QUE O SALDO ATUAL EM ESTOQUE
3 VERIFICAR SE O MATERIAL TEM SALDO EM 'ESTOQUE_LOTE'
4 VERIFICAR SE A QTD SAIDA E MENOR QUE SALDO DO LOTE

VERIFICACOES ENTRADA:

1 SE O MATERIAL EXISTE, REALIZAR O 'UPDATE'
2 SE O MATERIAL NÃO EXISTE, REALIZAR O 'INSERT'

TABELAS ENVOLVIDAS:

ESTOQUE
ESTOQUE_LOTE
ESTQUE_MOV

EXECOES RESULTAM EM ROLLBACK

*/

CREATE OR REPLACE PROCEDURE PROC_MOV_ESTOQUE (P_OPER IN VARCHAR2,
                                             P_EMP IN NUMBER,
                                             P_COD_MAT IN INT,
                                             P_LOTE IN VARCHAR2,
                                             P_QTD IN INT,
                                             P_DATA_MOV DATE)
                                             
IS

    EXC_MAT_N_EXISTE EXCEPTION;
    EXC_OPERACAO_NAO_PERMITIDA EXCEPTION;
    EXC_ESTOQUE_NEGATIVO EXCEPTION;
    EXC_ESTOQUE_NEGATIVO_LOTE EXCEPTION;
    
    V_SALDO_ESTOQUE INT;
    V_SALDO_ESTOQUE_LOTE INT;
    V_MAT_EXISTE INT ;
    V_REG_ESTOQUE INT;
    V_REG_ESTOQUE_LOTE INT;

BEGIN
    -- VERIFICAÇÃO DE PARÂMETROS
    
    -- VERIFICA SE OPERACAO É PERMITIDA;
    IF P_OPER NOT IN ('E','S') THEN
        RAISE EXC_OPERACAO_NAO_PERMITIDA;
    ELSE 
        dbms_output.put_line('VERIFICAÇÃO DE OPERACAO... OK!');
    END IF;
    
    -- VERIFICA SE MATERIAL EXISTE
    SELECT COUNT(*) INTO V_MAT_EXISTE 
    FROM MATERIAL 
    WHERE COD_MAT=P_COD_MAT AND COD_EMPRESA=P_EMP;
    
    IF V_MAT_EXISTE=0 THEN
        RAISE EXC_MAT_N_EXISTE;
    ELSE
        dbms_output.put_line('VERIFICAÇÃO DE MATERIAL... OK!');
    END IF;
  
    --VERIFICA SE EXISTE REGISTRO EM ESTOQUE
    SELECT COUNT(*) INTO V_REG_ESTOQUE 
    FROM ESTOQUE 
    WHERE COD_MAT=P_COD_MAT AND COD_EMPRESA=P_EMP;
  
    dbms_output.put_line('QTD REG ESTOQUE '||V_REG_ESTOQUE);
    
    -- OPERACAO PARA SAIDA
    
    -- VERIFICA SE OPERACAO DE SAIDA E SE MATERIAL EXISTE NO ESTOQUE
    IF P_OPER='S' AND V_REG_ESTOQUE=0 
    THEN
        RAISE EXC_ESTOQUE_NEGATIVO;
    ELSIF  P_OPER='S' AND V_REG_ESTOQUE>0  THEN
        -- ATRIBUI SALDO DE ESTOQUE E QTD REGISTRO
        SELECT QTD_SALDO,COUNT(*) INTO V_SALDO_ESTOQUE,V_REG_ESTOQUE 
        FROM ESTOQUE 
        WHERE COD_MAT=P_COD_MAT AND COD_EMPRESA=P_EMP
        GROUP BY QTD_SALDO;
        dbms_output.put_line('VERIFICAÇÃO DE ESTOQUE... OK!');
    END IF;
  
    --VERIFICA SE EXISTE REGISTRO EM ESTOQUE LOTE
    SELECT COUNT(*) INTO V_REG_ESTOQUE_LOTE 
    FROM ESTOQUE_LOTE 
    WHERE COD_MAT=P_COD_MAT AND LOTE=P_LOTE AND COD_EMPRESA=P_EMP;
    dbms_output.put_line('QTD REG ESTOQUE LOTE '||V_REG_ESTOQUE_LOTE);
    
    -- VERIFICA OPERACAO DE SAIDA E SE MATERIAL EXISTE NO ESTOQUE LOTE
    IF P_OPER='S' AND V_REG_ESTOQUE_LOTE=0 
    THEN
        RAISE EXC_ESTOQUE_NEGATIVO_LOTE;
    ELSIF P_OPER='S' AND V_REG_ESTOQUE_LOTE>0 THEN
        -- ATRIBUI SALDO DE ESTOQUE_LOTE E QTD REGISTRO
        SELECT SUM(QTD_LOTE),COUNT(*) INTO V_SALDO_ESTOQUE_LOTE,V_REG_ESTOQUE_LOTE 
        FROM ESTOQUE_LOTE 
        WHERE COD_MAT=P_COD_MAT AND LOTE=P_LOTE AND COD_EMPRESA=P_EMP;
        dbms_output.put_line('TEM ESTOQUE LOTE');
    END IF;
  
    IF P_OPER='S' AND  (V_SALDO_ESTOQUE_LOTE-P_QTD<0 OR V_SALDO_ESTOQUE-P_QTD<0) 
    THEN
        RAISE EXC_ESTOQUE_NEGATIVO_LOTE;
    ELSIF P_OPER='S' AND  V_SALDO_ESTOQUE_LOTE-P_QTD>=0 AND V_SALDO_ESTOQUE-P_QTD>=0 
    THEN
        -- ATUALIZA O ESTOQUE
        UPDATE ESTOQUE SET QTD_SALDO=QTD_SALDO-P_QTD 
        WHERE COD_MAT=P_COD_MAT AND COD_EMPRESA=P_EMP;
        
        -- ATUALIZA O ESTOQUE LOTE
        UPDATE ESTOQUE_LOTE SET QTD_LOTE=QTD_LOTE-P_QTD 
        WHERE COD_MAT=P_COD_MAT AND LOTE=P_LOTE AND COD_EMPRESA=P_EMP;
        
        -- INSERE O ESTOQUE TIP_MOV
        INSERT INTO ESTOQUE_MOV (id_mov,cod_empresa,tip_mov,cod_mat,lote,qtd,login,data_hora,DATA_MOV) VALUES
        (NULL,P_EMP,P_OPER,P_COD_MAT,P_LOTE,P_QTD,USER,SYSDATE,P_DATA_MOV);
        
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('OPERACAO DE SAÍDA FINALIZADA COM SUCESSO!');
    END IF;


    --OPERACAO PARA ENTRADA
    
    --VERIFCA SE MATERIAL TEM REGISTRO NO ESTOQUE E ESTOQUE LOTE
    IF P_OPER='E' AND V_REG_ESTOQUE_LOTE>0 AND V_REG_ESTOQUE>0 
    THEN
        -- ATUALIZA ESTOQUE
        UPDATE ESTOQUE SET QTD_SALDO=QTD_SALDO+P_QTD 
        WHERE COD_MAT=P_COD_MAT AND COD_EMPRESA=P_EMP;
        
        -- ATUALIZA ESTOQUE_LOTE
        UPDATE ESTOQUE_LOTE SET QTD_LOTE=QTD_LOTE+P_QTD 
        WHERE COD_MAT=P_COD_MAT AND LOTE=P_LOTE AND COD_EMPRESA=P_EMP;
        
        -- INSERE ESTOQUE TIP_MOV
        INSERT INTO ESTOQUE_MOV (id_mov,COD_EMPRESA,tip_mov,cod_mat,lote,qtd,login,data_hora,DATA_MOV) VALUES
            (NULL,P_EMP,P_OPER,P_COD_MAT,P_LOTE,P_QTD,USER,SYSDATE,P_DATA_MOV);
            
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('OPERACAO DE ENTRADA FINALIZADA COM SUCESSO!');

    -- VERIFICA QUE EXISTE ESTOQUE MAS NAO EXISTE ESTOQUE LOTE PARA INSERT ESTOQUE LOTE E UPDATE ESTOQUE
    ELSIF P_OPER='E' AND V_REG_ESTOQUE_LOTE=0 AND V_REG_ESTOQUE>0 
    THEN
        -- ATUALIZA ESTOQUE
        UPDATE ESTOQUE SET QTD_SALDO=QTD_SALDO+P_QTD 
        WHERE COD_MAT=P_COD_MAT AND COD_EMPRESA=P_EMP;
        
        --INSERE REGISTRO NA ESTOQUE LOTE
        INSERT INTO ESTOQUE_LOTE (COD_EMPRESA,COD_MAT,QTD_LOTE,LOTE) VALUES (P_EMP,P_COD_MAT,P_QTD,P_LOTE);
        
        -- INSERE ESTOQUE TIP_MOV
        INSERT INTO ESTOQUE_MOV (id_mov,COD_EMPRESA,tip_mov,cod_mat,lote,qtd,login,data_hora,DATA_MOV) VALUES
            (NULL,P_EMP,P_OPER,P_COD_MAT,P_LOTE,P_QTD,USER,SYSDATE,P_DATA_MOV);
        
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('OPERACAO DE ENTRADA FINALIZADA COM SUCESSO!');
        
        -- VERIFICA SE NAO EXISTE ESTOQUE E ESTOQUE LOTE PARA INSERT
    ELSIF P_OPER='E' AND V_REG_ESTOQUE_LOTE=0 AND V_REG_ESTOQUE=0 
    THEN
        -- INSERE ESTOQUE
        INSERT INTO  ESTOQUE (COD_EMPRESA,COD_MAT,QTD_SALDO) VALUES (P_EMP,P_COD_MAT,P_QTD);
        
        --INSERE REGISTRO NO ESTOQUE LOTE
        INSERT INTO ESTOQUE_LOTE (COD_EMPRESA,COD_MAT,QTD_LOTE,LOTE) VALUES (P_EMP,P_COD_MAT,P_QTD,P_LOTE);
        
        -- INSERE ESTOQUE TIP_MOV
        INSERT INTO ESTOQUE_MOV (id_mov,COD_EMPRESA,tip_mov,cod_mat,lote,qtd,login,data_hora,DATA_MOV) VALUES
            (NULL,P_EMP,P_OPER,P_COD_MAT,P_LOTE,P_QTD,USER,SYSDATE,P_DATA_MOV);
        
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('OPERACAO FINALIZADA');
    END IF;
    
--EXCESSOES

EXCEPTION

    WHEN EXC_OPERACAO_NAO_PERMITIDA THEN
        DBMS_OUTPUT.PUT_LINE('A OPERACAO DEVER SER "E" (ENTRADA) OU "S" (SAIDA)');
        ROLLBACK;
     
    WHEN EXC_MAT_N_EXISTE THEN
        DBMS_OUTPUT.PUT_LINE('O MATERIAL NAO EXISTE NO CADASTRO');
        ROLLBACK;
     
    WHEN EXC_ESTOQUE_NEGATIVO THEN
        DBMS_OUTPUT.PUT_LINE('ESTOQUE NEGATIVO, OPERACAO NAO PERMITIDA!');
        ROLLBACK;
     
    WHEN EXC_ESTOQUE_NEGATIVO_LOTE THEN
        DBMS_OUTPUT.PUT_LINE('ESTOQUE LOTE NEGATIVO, OPERACAO NAO PERMITIDA!');
        ROLLBACK;
    
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('REGISTRO NAO ENCONTRADO!');
        DBMS_OUTPUT.PUT_LINE('Linha: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
        ROLLBACK;
         
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CODIGO DO ERRO '||SQLCODE||' MSG '||SQLERRM);
        DBMS_OUTPUT.PUT_LINE('Linha: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
        ROLLBACK;
        
END;

-- ===============
-- TESTES
-- ===============

SET SERVEROUTPUT ON
--TESTES DE ENTRADA
--PARAMETROS OPERACAO,COD_EMPRESA,MATERIAL,LOTE,QTD
EXECUTE PROC_MOV_ESTOQUE ('E',1,1,'ABC',10,'01/01/2026');
EXECUTE PROC_MOV_ESTOQUE ('E',1,1,'ABC',15,'01/02/2026');
--TESTES DE SAÍDA
EXECUTE PROC_MOV_ESTOQUE ('S',1,1,'ABC',5,'13/02/2026');


SELECT * FROM ESTOQUE;
SELECT * FROM ESTOQUE_LOTE;
SELECT a.*,to_char(a.DATA_HORA,'dd/mm/yyyy hh24:mi:ss') data FROM ESTOQUE_MOV a;


/*
DELETE from ESTOQUE;
DELETE FROM ESTOQUE_LOTE;
DELETE FROM ESTOQUE_MOV;


SELECT to_char(DATA_HORA,'cc dd/mm/yyyy hh24:mi:ss') data FROM ESTOQUE_MOV;
SELECT to_char(sysdate,'cc dd/mm/yyyy hh24:mi:ss') data FROM dual;

SELECT to_char(sysdate,'cc dd/mm/yyyy hh24:mi:ss'),
       to_char(current_date,'cc dd/mm/yyyy hh24:mi:ss'),
       sysdate,
       current_date FROM dual;
*/