-- ========================
-- PROC_GERA_NF
-- ========================

-- PROCEDURE DE GERAÇÃO DE DADOS DE NOTAS FISCAIS

--TABELAS ORIGEM: PED_VENDAS, PED_VENDAS_ITENS, PED_COMPRAS, PED_COMPRAS_ITENS
--TABELAS DESTINO: NOTA_FISCAL, NOTA_FISCAL_ITENS
--PARAMETROS TIP_NF,DOCTO,CFOP,DATA_EMIS,DATA_ENTREGA

CREATE OR REPLACE PROCEDURE PROC_GERA_NF (P_EMP IN NUMBER,
                                           TIP_NF IN VARCHAR2,-- E = ENTRADA S = SAIDA
                                           DOCTO IN NUMBER, --NUMERO DO PEDIDO QUE SERA GERADO NFE
                                           CFOP VARCHAR2,
                                           DATA_EMIS DATE,
                                           DATA_ENTREGA DATE)
IS

    EXC_LANC_FUTURO  EXCEPTION;
    EXC_TIP_NF       EXCEPTION;
    EXC_PED_N_EXISTE EXCEPTION;
    EXC_QTD_PED_VEND EXCEPTION;
    EXC_QTD_PED_COMP EXCEPTION;
        
    V_SEQ_MAT INT;
    V_TOTAL_NFE NUMBER(10,2):=0;
    QTD_PED_V INT;
    QTD_PED_C INT;
    V_NUM_NF  NUMBER;
    V_DATA DATE := TRUNC(sysdate);
	 
BEGIN
    
    --VALIDAÇÕES INICIAIS
    
    --VERIFICA SE A DATA DA EMISSAO É MAIOR QUE A DATA ATUAL
    IF (DATA_EMIS>V_DATA) THEN
        RAISE EXC_LANC_FUTURO;	
    END IF;
        
    --VERIFICA O TIPO DE MOVIMENTO
    IF (TIP_NF NOT IN ('S','E')) THEN
        RAISE EXC_TIP_NF;
    END IF;
        
    --VERIFICA SE HÁ PEDIDOS DE VENDAS PARA EMITIR NF
    SELECT COUNT(*) QTD INTO QTD_PED_V FROM PED_VENDAS A
    WHERE A.NUM_PEDIDO=DOCTO
    AND A.COD_EMPRESA=P_EMP
    AND A.SITUACAO<>'F';
        
    IF (TIP_NF='S' AND QTD_PED_V=0) THEN	 
        RAISE EXC_QTD_PED_VEND;     
    END IF;
        
    --VERIFICA SE EXISTE PEDIDO DE COMPRA
    SELECT COUNT(*) QTD INTO QTD_PED_C FROM PED_COMPRAS A
    WHERE A.NUM_PEDIDO=DOCTO
    AND A.COD_EMPRESA=P_EMP
    AND A.SITUACAO<>'F';
        
    IF (TIP_NF='E' AND QTD_PED_C=0) THEN
        RAISE  EXC_QTD_PED_COMP;	   
    END IF;
        
    --INICIO NOTA FISCAL DE SAIDA
    IF TIP_NF='S' THEN
        --CURSOR FOR PARA LER PEDIDO DE SAIDA E MONTAR O CABEÇALHO DA NF
        FOR C_NF IN (
            SELECT A.COD_EMPRESA,A.NUM_PEDIDO,A.ID_CLIENTE ID_CLIFOR,A.COD_PAGTO
            FROM  PED_VENDAS A
            WHERE A.NUM_PEDIDO=DOCTO
            AND A.COD_EMPRESA=P_EMP
            AND A.SITUACAO<>'F'
        ) LOOP
    
            --INSERE DADOS DO CURSOR FOR C_NF
            INSERT INTO NOTA_FISCAL (COD_EMPRESA,NUM_NF,TIP_NF,COD_CFOP,ID_CLIFOR,COD_PAGTO,
                DATA_EMISSAO,DATA_ENTREGA,TOTAL_NF,INTEGRADA_FIN,INTEGRADA_SUP)
            VALUES (P_EMP,NULL,TIP_NF,CFOP,C_NF.ID_CLIFOR,C_NF.COD_PAGTO,DATA_EMIS,DATA_ENTREGA,0,'N','N')
            RETURNING NUM_NF INTO V_NUM_NF; --ATRIBUI O NÚMERO DA NF A 'V_NUM_NF' PARA USO FUTURO
                        
            --APRESENTA VALORES CABECALHO
            DBMS_OUTPUT.PUT_LINE('NUM_NF: '||V_NUM_NF||' Tip NFE: '||TIP_NF||' CFOP: '||CFOP||' COD CLIFOR: '||C_NF.ID_CLIFOR||' COD PAGTO: '||C_NF.COD_PAGTO||' DATA_EMIS: '||DATA_EMIS||'DATA_ENTREGA: '||DATA_ENTREGA);
        
            --CURSOR DE DETALHES NFE
            
            FOR C_NF_IT IN (
                SELECT A.SEQ_MAT,A.COD_MAT,A.QTD,A.VAL_UNIT 
                FROM PED_VENDAS_ITENS A
                WHERE A.NUM_PEDIDO=DOCTO
                AND COD_EMPRESA=P_EMP
                ORDER BY A.SEQ_MAT
            ) LOOP
            
                --INSERE DADOS DO CURSOR FOR C_NF_IT
                INSERT INTO NOTA_FISCAL_ITENS (COD_EMPRESA,NUM_NF,SEQ_MAT,COD_MAT,QTD,VAL_UNIT,PED_ORIG)
                VALUES (P_EMP,V_NUM_NF,C_NF_IT.SEQ_MAT,C_NF_IT.COD_MAT,C_NF_IT.QTD,C_NF_IT.VAL_UNIT,DOCTO);
                        
                --APRESENTA VALORES (SOMENTE NA VERSÃO DE TESTE)
                DBMS_OUTPUT.PUT_LINE ('SEQ: '||C_NF_IT.SEQ_MAT||' COD MAT: '||C_NF_IT.COD_MAT||' QTD:'||C_NF_IT.QTD||' VAL_UNIT: '||C_NF_IT.VAL_UNIT);
                
                --ATRIBUE VALORES
                V_TOTAL_NFE:=V_TOTAL_NFE+(C_NF_IT.QTD*C_NF_IT.VAL_UNIT);
        
            END LOOP; -- FECHA CURSOR C_NF_IT
          
            --ATUALIZA TOTAL NFE
            UPDATE NOTA_FISCAL SET TOTAL_NF=V_TOTAL_NFE WHERE NUM_NF=V_NUM_NF AND COD_EMPRESA=P_EMP;
            --ATUALIZA STATUS DA NF PARA 'F' (FECHADO) 
            UPDATE PED_VENDAS  SET SITUACAO='F' WHERE NUM_PEDIDO=DOCTO AND COD_EMPRESA=P_EMP;
                
        END LOOP; -- FECHA CURSOR C_NF

    --ELSEIF PARA INICIO DA NOTA FISCAL DE ENTRADA
    ELSIF TIP_NF='E' THEN
    
        FOR C_NF IN (SELECT A.COD_EMPRESA,A.NUM_PEDIDO,A.ID_FOR AS ID_CLIFOR,A.COD_PAGTO
            FROM  PED_COMPRAS A
            WHERE A.NUM_PEDIDO=DOCTO
            AND A.COD_EMPRESA=P_EMP
            AND A.SITUACAO<>'F'
        ) LOOP
     
            --INSERE DADOS DO CURSOR FOR
            INSERT INTO NOTA_FISCAL (COD_EMPRESA,NUM_NF,TIP_NF,COD_CFOP,ID_CLIFOR,
                COD_PAGTO,DATA_EMISSAO,DATA_ENTREGA,TOTAL_NF,INTEGRADA_FIN,INTEGRADA_SUP)
            VALUES (P_EMP,NULL,TIP_NF,CFOP,C_NF.ID_CLIFOR,C_NF.COD_PAGTO,DATA_EMIS,
                DATA_ENTREGA,0,'N','N')
            RETURNING NUM_NF INTO V_NUM_NF; --PEGA O VALOR DA NFE INSERIDO E ATRIBUI O VALOR A 'V_NUM_NF'
                    
            --APRESENTA VALORES CABECALHO (SOMENTE NA VERSÃO DE TESTE)
            DBMS_OUTPUT.PUT_LINE('NUM_NF: '||V_NUM_NF||'Tip NFE: '||TIP_NF||' CFOP: '||CFOP||' COD CLIFOR: '||C_NF.ID_CLIFOR||'COD PAGTO: '||C_NF.COD_PAGTO||' DATA_EMIS: '|| DATA_EMIS||'DATA_ENTREGA: '||DATA_ENTREGA);
    
            --CURSOR DETALHE PED INICIO
            FOR C_NF_IT IN (
                SELECT A.SEQ_MAT,A.COD_MAT,A.QTD,A.VAL_UNIT 
                FROM PED_COMPRAS_ITENS A
                WHERE A.NUM_PEDIDO=DOCTO
                AND COD_EMPRESA=P_EMP
                ORDER BY A.SEQ_MAT
            ) LOOP
    
                INSERT INTO NOTA_FISCAL_ITENS (COD_EMPRESA,NUM_NF,SEQ_MAT,COD_MAT,QTD,
                    VAL_UNIT,PED_ORIG)
                VALUES (P_EMP,V_NUM_NF,C_NF_IT.SEQ_MAT,C_NF_IT.COD_MAT,C_NF_IT.QTD,
                    C_NF_IT.VAL_UNIT,DOCTO);
                    
                --APRESENTA VALORES (SOMENTE NA VERSÃO DE TESTE)
                DBMS_OUTPUT.PUT_LINE ('SEQ: '||C_NF_IT.SEQ_MAT||'COD MAT: '||C_NF_IT.COD_MAT||'QTD: '||C_NF_IT.QTD||' VAL_UNIT: '||C_NF_IT.VAL_UNIT);
                
                --ATRIBUE VALORES
                V_TOTAL_NFE:=V_TOTAL_NFE+(C_NF_IT.QTD*C_NF_IT.VAL_UNIT);
    
            END LOOP; -- FECHA CURSOR C_NF_IT
      
            --ATUALIZA TOTAL NFE
            UPDATE NOTA_FISCAL SET TOTAL_NF=V_TOTAL_NFE 
            WHERE NUM_NF=V_NUM_NF AND COD_EMPRESA=P_EMP;
            
            --ATUALIZA STATUS PARA FECHADO NFE
            UPDATE PED_COMPRAS  SET SITUACAO='F' 
            WHERE NUM_PEDIDO=DOCTO AND COD_EMPRESA=P_EMP;
        
        END LOOP; --FINAL CURSOR NFE
  
    END IF;
	
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('OPERAÇÃO REALIZADA COM SUCESSO!');
  
    EXCEPTION
        WHEN EXC_LANC_FUTURO THEN
            DBMS_OUTPUT.PUT_LINE('NAO É PERMITIDO LANCAMENTOS FUTUROS!'); 
        ROLLBACK;
    
        WHEN EXC_TIP_NF THEN
            DBMS_OUTPUT.PUT_LINE('OPERACAO NAO PERMITIDA!');
        ROLLBACK;
         
        WHEN  EXC_QTD_PED_VEND THEN
            DBMS_OUTPUT.PUT_LINE('NAO HÁ PEDIDO DE VENDAS DISPONIVEL PARA SAIDA!');     
        ROLLBACK;
        
        WHEN  EXC_QTD_PED_COMP THEN
            DBMS_OUTPUT.PUT_LINE('NAO HÁ PEDIDO DE COMPRAS DISPONIVEL PARA ENTRADA!');
        
        WHEN  NO_DATA_FOUND  THEN
            DBMS_OUTPUT.PUT_LINE('DADOS NÃO ENCONTRADOS!');
        
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('OUTROS CODIGO DO ERRO '||SQLCODE||' MSG '||SQLERRM);
            DBMS_OUTPUT.PUT_LINE('Linha: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
        ROLLBACK;

END;


-- ==============
-- TESTES
-- ==============                              

/*
--PARAMENTROS

P_EMP IN NUMBER,    (CODIGO DA EMPRESA)
TIP_NF IN CHAR(1),  (TIPO DE NF ('E' = ENTRADA 'S' = SAIDA))
DOCTO IN NUMBER,    (NÚMERO DO PEDIDO QUE SERÁ GERADO A NFE)
CFOP VARCHAR2,      (CÓDIGO FISCAL DE OPERAÇÕES E PRESTAÇÕES... 4 DÍGITOS)
DATA_EMIS DATE,     (DATA DA EMISSÃO... DEVE SER IGUAL A DATA ATUAL)
DATA_ENTREGA        (DATA DA ENTREGA)
*/

SET SERVEROUTPUT ON 

-- TESTES GERAÇÃO DE NF DE PEDIDOS DE SAÍDA
EXECUTE PROC_GERA_NF (1,'S',1,'5.101','26/05/2026','27/05/2026');
EXECUTE PROC_GERA_NF (1,'S',2,'5.101','26/05/2026','27/05/2026');
EXECUTE PROC_GERA_NF (1,'S',3,'5.101','26/05/2026','27/05/2026');
EXECUTE PROC_GERA_NF (1,'S',4,'5.101','26/05/2026','27/05/2026');

-- TESTES GERAÇÃO DE NF DE PEDIDOS DE ENTRADA
EXECUTE PROC_GERA_NF (1,'E',1,'1.101','26/05/2026','27/05/2026');
EXECUTE PROC_GERA_NF (1,'E',2,'1.101','26/05/2026','27/05/2026');

/*
SELECT COD_EMPRESA,NUM_PEDIDO,SITUACAO FROM PED_VENDAS;
SELECT  COD_EMPRESA,NUM_PEDIDO,SITUACAO FROM PED_COMPRAS;

SELECT * FROM PED_VENDAS;
SELECT * FROM PED_COMPRAS;
SELECT * FROM PED_VENDAS_ITENS;
SELECT * FROM PED_COMPRAS_ITENS WHERE COD_EMPRESA=1 AND NUM_PEDIDO=1;

DELETE FROM NOTA_FISCAL_ITENS;
DELETE FROM NOTA_FISCAL;

UPDATE  PED_VENDAS SET SITUACAO='P' WHERE SITUACAO='F' ;
UPDATE  PED_COMPRAS SET SITUACAO='P' WHERE SITUACAO='F' ;
*/