-- ========================
-- PROC_INTEGR_NF_ESTOQUE
-- ========================

-- PROCEDURE DE INTEGRAÇÃO DE NOTAS FISCAIS E ESTOQUE

CREATE OR REPLACE PROCEDURE PROC_INTEGR_NF_ESTOQUE (P_EMP IN NUMBER,
                                                    P_NUM_NF NUMBER,
                                                    P_DATA_MOVTO DATE)
IS

    V_EXC_SALDO_INSUFICIENTE EXCEPTION;
    V_EXC_DOCT_NAO_EXISTE EXCEPTION;
    V_EXC_INTEGRADO EXCEPTION;
        
    V_QTD_AUX NUMBER(10,2);
    V_QTD_TOT NUMBER(10,2);
    V_TIP_OPER VARCHAR2(1);
    V_SITUA VARCHAR2(1);
    V_CONT INT;
    V_NUM_NF NUMBER;
    V_MAT_AUX NUMBER;
    V_SALDO_AUX NUMBER(10,2);

BEGIN 
    
    --VERIFICA SE DOCTO EXISTE E SE JA ESTA INTEGRADO
    SELECT NUM_NF,TIP_NF,INTEGRADA_SUP, COUNT(*) QTD 
    INTO V_NUM_NF,V_TIP_OPER,V_SITUA,V_CONT 
    FROM NOTA_FISCAL
    WHERE COD_EMPRESA=P_EMP AND NUM_NF=P_NUM_NF
    GROUP BY NUM_NF,TIP_NF,INTEGRADA_SUP;
  --VERIFICA O DOCTO
    IF V_CONT=0 THEN
        RAISE V_EXC_DOCT_NAO_EXISTE;
    END IF;

    --VERIFICA SE O DOCTO E SE JA ESTA INTEGRADO
    IF V_CONT=1 AND V_SITUA='S' THEN
        RAISE V_EXC_INTEGRADO;
    END IF;
  
    --VERIFICA SE HÁ NOTA DE ENTRADA PARA DAR ENTRADA EM ESTOQUE;
    IF V_TIP_OPER='E' THEN
        -- CURSOR PARA MANIPULAR OS DADOS DE NFs NA PROCEDURE DE ESTOQUE
        FOR C_NF_IT IN (
            SELECT A.COD_EMPRESA,A.TIP_NF,B.COD_MAT,
            TO_CHAR(SYSDATE,'DD-MM')||'-'||A.NUM_NF LOTE, B.QTD --COMPOSICAO CAMPO LOTE (DIA MES + NUMERO DA NF)
			FROM NOTA_FISCAL A
            INNER JOIN NOTA_FISCAL_ITENS B
			ON A.COD_EMPRESA=B.COD_EMPRESA
            AND A.NUM_NF=B.NUM_NF
			WHERE A.NUM_NF=P_NUM_NF --PARAMETRO
            AND A.COD_EMPRESA=P_EMP --PARAMENTO
            AND A.TIP_NF='E'
			AND A.INTEGRADA_SUP='N'
        ) LOOP
            --CHAMA A PROCEDURE DE ESTOQUE QUE MOVIMENTA ESTOQUE PARA DAR ENTRADA NO MATERIAL
            PROC_MOV_ESTOQUE (C_NF_IT.TIP_NF,P_EMP,C_NF_IT.COD_MAT,C_NF_IT.LOTE,
            C_NF_IT.QTD,P_DATA_MOVTO);
        END LOOP;
        
        -- ATUALIZA O STATUS DA INTEGRAÇÃO ENTRE NF E ESTOQUE
        UPDATE NOTA_FISCAL SET INTEGRADA_SUP='S' 
        WHERE NUM_NF=P_NUM_NF 
        AND COD_EMPRESA=P_EMP;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE ('ENTRADA CONCLUIDA!'); --SOMENTE PARA FINS DIDÁTICOS 
    
    --INICIO DA OPERACAO DE SAIDA
    
    --OBS: REGRA - NAO PODE SAIR MAIS QUE O SALDO ATUAL
    --OBS2: IMPLEMENTAÇÃO DO MÉTODO FIFO PARA OS LOTES
    ELSIF V_TIP_OPER='S' THEN
        -- CURSOR PARA MANIPULAR DADOS DAS NFs
        FOR C_NF_IT IN (
            SELECT A.COD_EMPRESA,A.TIP_NF,B.COD_MAT,B.QTD 
            FROM NOTA_FISCAL A
            INNER JOIN NOTA_FISCAL_ITENS B
            ON A.COD_EMPRESA=B.COD_EMPRESA
            AND A.NUM_NF=B.NUM_NF
            AND A.COD_EMPRESA=P_EMP --PARAMENTO
            WHERE A.NUM_NF=P_NUM_NF --PARAMETRO
            AND A.TIP_NF='S'
            AND A.INTEGRADA_SUP='N'
        ) LOOP 
            --CURSOR PARA MANIPULAR DADOS SOBRE O ESTQUE
            FOR C_ESTOQUE IN (
                SELECT A.COD_EMPRESA,A.COD_MAT,A.QTD_SALDO 
                FROM ESTOQUE A
                WHERE A.COD_EMPRESA=P_EMP 
                AND A.COD_MAT=C_NF_IT.COD_MAT
            ) LOOP
                --VERIFICA SE HÁ SALDO SUFICIENTE PARA A OPERAÇÃO DE SAIDA                
                IF (C_NF_IT.QTD>C_ESTOQUE.QTD_SALDO) THEN
                    RAISE V_EXC_SALDO_INSUFICIENTE;
                END IF;
            END LOOP; --LOOP C_ESTOQUE
        END LOOP; --LOOP C_NF_IT  
    END IF;  
    
    --GERA MOVIMENTAÇÃO DE SAIDA
    IF V_TIP_OPER='S' THEN
    --ABRE CURSOR DOS ITENS DA NF
        FOR C_NF_IT IN (
            SELECT A.COD_EMPRESA,A.TIP_NF,B.COD_MAT,B.QTD 
			FROM NOTA_FISCAL A
			INNER JOIN NOTA_FISCAL_ITENS B
			ON A.COD_EMPRESA=B.COD_EMPRESA
            AND A.NUM_NF=B.NUM_NF
            AND A.COD_EMPRESA=P_EMP --PARAMENTO
			WHERE A.NUM_NF=P_NUM_NF --PARAMETRO
            AND A.TIP_NF='S'
			AND A.INTEGRADA_SUP='N'
        ) LOOP
    
            --ATRIBUI A QUANTIDADE NECESSARIA PARA BAIXA EM ESTOQUE
            V_SALDO_AUX:=C_NF_IT.QTD;
            --CURSOR PARA VERIFICAR O ESTOQUE DE CADA LOTE
            FOR C_EST_LOTE IN (
                SELECT A.COD_EMPRESA,A.COD_MAT,A.LOTE,A.QTD_LOTE 
                FROM ESTOQUE_LOTE A
                WHERE A.COD_EMPRESA=P_EMP 
                AND A.COD_MAT=C_NF_IT.COD_MAT 
                ORDER BY A.COD_MAT,A.LOTE 
            ) LOOP
                --SE SALDO IGUAL A ZERO LER PROXIMO MATERIAL
                IF V_SALDO_AUX=0 THEN
                    EXIT;
                END IF;
        
                IF (V_SALDO_AUX<=C_EST_LOTE.QTD_LOTE) THEN
                    --CHAMA A PROCEDURE DE MOVIMENTAÇÃO DE ESTOQUE
                    PROC_MOV_ESTOQUE (C_NF_IT.TIP_NF,P_EMP,C_EST_LOTE.COD_MAT,
                        C_EST_LOTE.LOTE,V_SALDO_AUX,P_DATA_MOVTO);
                    --SUBSTRAINDO QTD BAIXADA
                    V_SALDO_AUX:=V_SALDO_AUX-V_SALDO_AUX;   
                ELSIF (V_SALDO_AUX>C_EST_LOTE.QTD_LOTE) THEN
                    --EXECUTA PROCEDURE QUE MOVIMENTA ESTOQUE
                    PROC_MOV_ESTOQUE (C_NF_IT.TIP_NF,P_EMP,C_EST_LOTE.COD_MAT,
                        C_EST_LOTE.LOTE,C_EST_LOTE.QTD_LOTE,P_DATA_MOVTO);        
                    V_SALDO_AUX:=V_SALDO_AUX-C_EST_LOTE.QTD_LOTE;
                END IF;
            END LOOP; --C_EST_LOTE
        END LOOP; --C_NF_IT
    
        UPDATE NOTA_FISCAL SET INTEGRADA_SUP='S'
        WHERE NUM_NF=P_NUM_NF AND COD_EMPRESA=P_EMP;
        
        COMMIT;
		DBMS_OUTPUT.PUT_LINE ('SAIDA CONCLUIDA!'); --SOMENTE PARA FINS DIDÁTICOS
    END IF;
    
    --EXCEPTION
    EXCEPTION
        WHEN V_EXC_SALDO_INSUFICIENTE THEN
            DBMS_OUTPUT.PUT_LINE('SALDO INSUFICIENTE!'); 
        ROLLBACK;
        
        WHEN V_EXC_DOCT_NAO_EXISTE THEN
            DBMS_OUTPUT.PUT_LINE('DOCUMENTO NAO EXISTE!');
        ROLLBACK;
                   
        WHEN  V_EXC_INTEGRADO THEN
            DBMS_OUTPUT.PUT_LINE('DOCTO JA INTEGRADO!');     
        ROLLBACK;
            
        WHEN  NO_DATA_FOUND  THEN
            DBMS_OUTPUT.PUT_LINE('NAO EXISTE DADOS!');
        ROLLBACK;
            
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('OUTROS CODIGO DO ERRO '||SQLCODE||' MSG '||SQLERRM);
            DBMS_OUTPUT.PUT_LINE('Linha: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
        ROLLBACK;

END;     


--=========================
-- TESTES
-- ========================

--SELECT * FROM NOTA_FISCAL
--UPDATE NOTA_FISCAL SET INTEGRADA_SUP='N'

--SIMULAÇÃO DE ENTRADA
--PARAMENTROS (P_EMP IN NUMBER, P_NUM_NF NUMBER, P_DATA_MOVT
EXECUTE PROC_INTEGR_NF_ESTOQUE (1,2,'28/05/2026');

--ALIMENTA O ESTOQUE PARA NOTA DE SAIDA
-- SIMULAÇÃO DE MOVIMENTAÇÃO DE ESTOQUE
EXECUTE PROC_MOV_ESTOQUE ('E',1,1,'AB',20,SYSDATE);
EXECUTE PROC_MOV_ESTOQUE ('E',1,1,'CD',15,SYSDATE);
EXECUTE PROC_MOV_ESTOQUE ('E',1,2,'EF',20,SYSDATE);
EXECUTE PROC_MOV_ESTOQUE ('E',1,2,'GH',20,SYSDATE);

--PARAMENTROS (P_EMP IN NUMBER, P_NUM_NF NUMBER, P_DATA_MOVT
SET SERVEROUTPUT ON
--TESTE DA PROCEDURE DE SAÍDA
EXECUTE PROC_INTEGR_NF_ESTOQUE (1,1,'28/05/2026');

/*
SELECT * FROM ESTOQUE;
SELECT * FROM ESTOQUE WHERE COD_MAT IN (1,2);
SELECT * FROM ESTOQUE WHERE COD_MAT IN (1,2) AND COD_EMPRESA=1;
SELECT * FROM ESTOQUE_LOTE WHERE COD_MAT IN (1,2) AND COD_EMPRESA=1;
SELECT * FROM ESTOQUE_MOV ORDER BY ID_MOV;
SELECT * FROM ESTOQUE_LOTE;

SELECT * FROM PED_VENDAS_ITENS;
SELECT * FROM PED_VENDAS;
SELECT * FROM PED_COMPRAS;
SELECT * FROM NOTA_FISCAL ORDER BY NUM_NF;
SELECT * FROM NOTA_FISCAL_ITENS WHERE COD_EMPRESA=1 AND NUM_NF='1' ORDER BY NUM_NF;
*/
