-- ========================
-- PROC_APONTAMENTO
-- ========================

-- PROCEDURE DE APONTAMENTO DE PRODUÇÃO

/*
OBJETIVOS:

GERAR MOVIMENTO DE ENTRADA NO ESTOQUE DO PRODUTO APONTADO;
GERAR MOVIMENTO DE SAIDA NO ESTOQUE DOS PRODUTOS CONSUMIDOS CONFORME FICHA TECNICA;
ALIMENTAR A TABELA DE CONSUMO PARA RASTREABILIDADE;
ALIMENTAR A TABELA DE APONTAMENTO PARA RASTREABILIDADE;
ATUALIZAR TABELAS 'ORDEM_PROD', 'QTD_PROD' E 'SITUACAO=F'(FINALIZADO), QUANDO 'QTD_PLAN'='QTD_PROD'

PARAMETROS: 'ID_ORDEM','COD_MAT_PROD','QTD_APONT','LOTE'

CONSISTENCIAS DE ESTOQUE:

'ORDEM_PROD' = 'A' (NAO GEROU PEDIDO DE COMPRAS)
'ORDEM_PROD' = 'P' (GEROU PEDIDO DE COMPRAS)
'ORDEM_PROD' = 'F' (FINALIZADA)
*/

CREATE OR REPLACE PROCEDURE PROC_APONTAMENTO (P_EMP IN NUMBER,          --ID DA EMPRESA
                                              P_ID_ORDEM IN INT,        --ID DA ORDEM DE PRODUCAO
                                              P_COD_MAT_PROD IN NUMBER, --CODIGO DO MATERIAL PRODUZIDO
                                              P_QTD_APON IN NUMBER,     --QUANTIDADE APONTADA
                                              P_LOTE_PROD VARCHAR2)     --LOTE PRODUZIDO

IS

    V_ORDER_N_EXISTE    EXCEPTION;
    V_MAT_NEC_INSUF     EXCEPTION;
    V_SALDO_INSUF_ORDEM EXCEPTION;
        
    V_CONT_OP INT;
    
    P_QTD_PLAN DECIMAL(10,2);
    P_QTD_PROD DECIMAL(10,2);
    P_SALDO DECIMAL(10,2);
    P_SALDO_AUX DECIMAL(10,2);
    P_DATA_MOVTO DATE;
    P_ID_APON INT;
    P_QTD_ATEND DECIMAL(10,2);
    P_COD_MAT_AUX INT;

BEGIN 

--ETAPA DE VERIFICACOES E VALIDACOES

    --ATRIBUINDO VALOR A VARIAVEL P_DATA_MOVTO
    SELECT SYSDATE INTO P_DATA_MOVTO FROM DUAL;

    --PRIMEIRA ETAPA DO APONTAMENTO (ATUALIZA ORDEM E MOVIMENTA ESTOQUE)
    
    --VERIFICA SE EXISTE ORDEM E SE POSSUI SALDO PARA SELECAO
    SELECT COUNT(*) CONT,A.QTD_PLAN,A.QTD_PROD INTO V_CONT_OP,P_QTD_PLAN,P_QTD_PROD 
    FROM ORDEM_PROD A
    WHERE A.COD_MAT_PROD=P_COD_MAT_PROD
        AND A.ID_ORDEM=P_ID_ORDEM
        AND A.COD_EMPRESA=P_EMP
        AND A.SITUACAO='P'
    GROUP BY A.QTD_PLAN,A.QTD_PROD; --APENAS ORDEM PLANEJADAS
    
    --ATRIBUINDO SALDO
    P_SALDO:=P_QTD_PLAN-P_QTD_PROD;
    
    --VERIFICA SE EXISTE ORDEM
    IF V_CONT_OP=0 THEN
        RAISE V_ORDER_N_EXISTE;   
        --VERIFICA SE EXISTE SALDO SUFICIENTE PARA A PRODUCAO PLANEJADA
    ELSIF V_CONT_OP=1 AND P_SALDO<P_QTD_APON THEN 
        RAISE V_SALDO_INSUF_ORDEM;
    END IF;
	
    
    --CURSOR QUE VERIFICA SE MATERIAIS NECESSARIOS TEM SALDO PARA CONSUMO
    FOR C_MAT_NECES IN(
        SELECT  B.COD_MAT_NECES,
                B.QTD_NECES*P_QTD_APON AS QTD_NECES,
                NVL(C.QTD_SALDO,0) SALDO, -- TRATA O VALOR NULO CASO SALDO ZERADO
                NVL(C.QTD_SALDO,0)-(B.QTD_NECES*P_QTD_APON) AS SALDO_DISP
	    FROM ORDEM_PROD A
        INNER JOIN FICHA_TECNICA B ON A.COD_MAT_PROD=B.COD_MAT_PROD
            AND A.COD_EMPRESA=B.COD_EMPRESA  
        LEFT JOIN  ESTOQUE C ON B.COD_MAT_NECES=C.COD_MAT
            AND A.COD_EMPRESA=B.COD_EMPRESA   
        WHERE A.ID_ORDEM=P_ID_ORDEM --PARAMENTRO DE OP
            AND A.COD_EMPRESA=P_EMP
    ) LOOP --PARAMENTRO DE EMRPESA	
        --VERIFICOES
        IF C_MAT_NECES.SALDO_DISP<=0 THEN  
            RAISE V_MAT_NEC_INSUF;      
        END IF; 
    END LOOP;
    
--ETAPA DE APONTAMENTO
	
    --CURSOR DE APONTAMENTO, MOVIMENTACAO DE ESTOQUE E ATUALIZACAO DE ORDEM DE PRODUCAO
    FOR C_APONT IN (
        SELECT A.ID_ORDEM,A.COD_MAT_PROD,A.QTD_PLAN,A.QTD_PROD
	    FROM ORDEM_PROD A
	    WHERE A.COD_MAT_PROD=P_COD_MAT_PROD
	        AND ID_ORDEM=P_ID_ORDEM
            AND A.COD_EMPRESA=P_EMP
	        AND A.SITUACAO='P'
    )LOOP --APENAS ORDEM PLANEJADAS
    
        --ATRIBUINDO VALORES
        P_SALDO:=C_APONT.QTD_PLAN-C_APONT.QTD_PROD;
        P_SALDO_AUX:=P_SALDO;	
	
        --INSERT NA TABELA APONTAMENTOS PARA RASTREABILIDADE
        
        INSERT INTO APONTAMENTOS (COD_EMPRESA,ID_APON,ID_ORDEM,COD_MAT_PROD,QTD_APON,DATA_APON,LOGIN,LOTE)
        VALUES (P_EMP,NULL,P_ID_ORDEM,P_COD_MAT_PROD,P_QTD_APON,SYSDATE,USER,P_LOTE_PROD)
        RETURNING ID_APON INTO P_ID_APON;
		
        --EXECUTA A PROCEDURE DE MOVIMENTACAO DE ENTRADA 'E' DE ESTOQUE
        PROC_MOV_ESTOQUE ('E',P_EMP,P_COD_MAT_PROD,P_LOTE_PROD,P_QTD_APON,P_DATA_MOVTO);

        --VUSUALIZACAO SOMENTE PARA FINS DIDATICOS
        DBMS_OUTPUT.PUT_LINE('APONTAMENTO');
        DBMS_OUTPUT.PUT_LINE('ORDEM: '||P_ID_ORDEM||' MAT PRODUZIDO: '||P_COD_MAT_PROD||' QTD: '||P_QTD_APON||' LOTE: '||P_LOTE_PROD );
       
        --UPDATE DA ORDEM DE PRODUCAO
        UPDATE ORDEM_PROD SET QTD_PROD=P_QTD_PROD+P_QTD_APON
        WHERE ID_ORDEM=P_ID_ORDEM
            AND COD_MAT_PROD=P_COD_MAT_PROD
            AND COD_EMPRESA=P_EMP;
		
        --ATRIBUICAO DE VALORES
        P_SALDO:=P_QTD_PLAN-(C_APONT.QTD_PROD+P_QTD_APON);
        P_SALDO_AUX:=P_SALDO;
    END LOOP; --FIM FIM LOOP APONTAMENTO	
	
    --VUSUALIZACAO SOMENTE PARA FINS DIDATICOS
    DBMS_OUTPUT.PUT_LINE('MATERIAS CONSUMIDOS');
	       
    --CURSOR DE APONTAMENTO DO MATERIAL NECESSARIO PARA A PRODUCAO
    FOR C_NECESSIDADES IN (
        SELECT A.ID_ORDEM,A.SITUACAO,A.COD_MAT_PROD,
            A.QTD_PLAN,B.COD_MAT_NECES,B.QTD_NECES,
            P_QTD_APON QTD_APON,
            P_QTD_APON*B.QTD_NECES QTD_NECES_CONS
        FROM ORDEM_PROD A
        INNER JOIN FICHA_TECNICA B
        ON A.COD_MAT_PROD=B.COD_MAT_PROD
            AND A.COD_EMPRESA=B.COD_EMPRESA 
        WHERE A.SITUACAO='P'
            AND A.ID_ORDEM=P_ID_ORDEM --PARAMENTRO DE ORDEM
            AND A.COD_MAT_PROD=P_COD_MAT_PROD --PARAMETEO MAT PROD
            AND A.COD_EMPRESA=P_EMP 
    ) LOOP

        --CURSOR DE ALIMENTACAO DO CONSUMO DE PRODUCAO E MOVIMENTACAO DO ESTOQUE
        FOR C_EST_CONS IN (
            SELECT C.COD_MAT,C.QTD_LOTE,C.LOTE
            FROM  ESTOQUE_LOTE C
            WHERE C.COD_MAT=C_NECESSIDADES.COD_MAT_NECES
                AND C.COD_EMPRESA=P_EMP --PARAMENTRO EMPRESA
                AND C.QTD_LOTE>0
            ORDER BY C.COD_MAT,C.LOTE
        ) LOOP
            
            --ATRIBUICAO DE VALORES
            P_SALDO:=C_NECESSIDADES.QTD_NECES_CONS;
            P_SALDO_AUX:=P_SALDO;
    
            --VERIFICA A TROCA DE MATERIAL
            IF P_COD_MAT_AUX<>C_NECESSIDADES.COD_MAT_NECES THEN   
                P_QTD_ATEND:=0;
            END IF;
            
            --VERIFICACOES SE SALDO	 <= 0	 
            IF P_SALDO<=0 THEN
                P_QTD_ATEND:=0;
            END IF;
            
            --VERIFICA RELACAO ENTRE SALDO_AUX E QTD_LOTE
            IF  P_SALDO_AUX>=C_EST_CONS.QTD_LOTE THEN
                P_QTD_ATEND:=C_EST_CONS.QTD_LOTE;
                P_SALDO:=P_SALDO-C_NECESSIDADES.QTD_NECES_CONS;
                P_SALDO_AUX:=P_SALDO_AUX-C_EST_CONS.QTD_LOTE;
            ELSIF  P_SALDO_AUX<C_EST_CONS.QTD_LOTE THEN
                P_SALDO:=C_NECESSIDADES.QTD_NECES_CONS;
                P_QTD_ATEND:=P_SALDO_AUX;
                P_SALDO_AUX:=P_SALDO_AUX-P_QTD_ATEND;
            END IF;
            
            --VERIFICACAO A CONDICAO PARA PROCEDER A MOVIMENTACAO DE SAIDA DE ESTOQUE
            IF P_SALDO_AUX>=0 AND P_QTD_ATEND>0 THEN
                --INSERT NA TABELA CONSUMO PARA RASTREABILIDADE
                INSERT INTO CONSUMO VALUES (P_ID_APON,P_EMP,C_NECESSIDADES.COD_MAT_NECES,P_QTD_ATEND,C_EST_CONS.LOTE);
            
                --EXECUTA PROCEDURE DE MOVIMENTACAO DE ESTOQUE COM MOV SAIDA 'S'
                PROC_MOV_ESTOQUE ('S',P_EMP,C_NECESSIDADES.COD_MAT_NECES,C_EST_CONS.LOTE,P_QTD_ATEND,P_DATA_MOVTO);
                P_COD_MAT_AUX:=C_NECESSIDADES.COD_MAT_NECES;
                --VUSUALIZACAO SOMENTE PARA FINS DIDATICOS
                DBMS_OUTPUT.PUT_LINE('COD MAT: '||C_NECESSIDADES.COD_MAT_NECES||' QTD ATEND: '||P_QTD_ATEND||' LOTE: '||C_EST_CONS.LOTE||' SALDO AUX: '||P_SALDO_AUX);
            END IF;
            
            --SE SALDO AUX IGUAL A ZERO, SAI DO LOOP E INICIA PROXIMO MATERIAL OU FINALIZA  
            IF  P_SALDO_AUX=0 THEN
               EXIT;
            END IF;   
      
        END LOOP;
    END LOOP;
  
    COMMIT;
    
    --VUSUALIZACAO SOMENTE PARA FINS DIDATICOS
    DBMS_OUTPUT.PUT_LINE('FINALIZADO COM SUCESSO!');

    EXCEPTION
    WHEN V_ORDER_N_EXISTE THEN
        DBMS_OUTPUT.PUT_LINE('ORDEM NAO EXISTE OU SEM SALDO/PARAMETROS INCORRETOS');
    ROLLBACK;
    
    WHEN V_MAT_NEC_INSUF THEN
        DBMS_OUTPUT.PUT_LINE('MATERIAIS NECESSARIOS INSUFICENTE');
    ROLLBACK;
    
    WHEN V_SALDO_INSUF_ORDEM THEN
        DBMS_OUTPUT.PUT_LINE('SALDO INSUFICIENTE DA ORDEM');
    ROLLBACK;
         
    WHEN  NO_DATA_FOUND  THEN
        DBMS_OUTPUT.PUT_LINE('NAO EXISTE DADOS!');
    ROLLBACK;
        
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('OUTROS CODIGO DO ERRO '||SQLCODE||' MSG '||SQLERRM);
        DBMS_OUTPUT.PUT_LINE('Linha: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    ROLLBACK;

END; 



--=========================
-- TESTES
-- ========================

--VERIFICA ORDEM
SELECT * FROM ORDEM_PROD
WHERE ID_ORDEM=3 AND COD_EMPRESA=1;

--VERIFICA ESTOQUE
SELECT * FROM ESTOQUE WHERE COD_EMPRESA=1 AND COD_MAT=1;

SELECT * FROM ESTOQUE_LOTE WHERE COD_EMPRESA=1 AND COD_MAT=1;


--VERIFICA APONTAMENTOS
SELECT * FROM APONTAMENTOS
WHERE COD_EMPRESA=1 AND ID_ORDEM=3;

--VERIFACA CONSUMOS
SELECT * FROM CONSUMO
WHERE ID_APON=2
AND COD_EMPRESA=1;
 
--VERIFICA SE MATERIAL NECESSARIO EXISTE PARA A ORDEM 3 DA EMPRESA 1
SELECT  A.COD_EMPRESA,A.ID_ORDEM,A.COD_MAT_PROD,A.QTD_PLAN,A.QTD_PROD,
        A.QTD_PLAN-A.QTD_PROD SALDO,
        B.COD_MAT_NECES,D.DESCRICAO,
        B.QTD_NECES,
        (A.QTD_PLAN-A.QTD_PROD)*B.QTD_NECES QTD_REAL_NEC,
        NVL(C.QTD_SALDO,0) AS QTD_SALDO,
    CASE WHEN  (A.QTD_PLAN-A.QTD_PROD)*B.QTD_NECES>NVL(C.QTD_SALDO,0)
        THEN 'FALTA ESTOQUE' 
        ELSE 'OK' END MSG
    FROM ORDEM_PROD A
    INNER JOIN FICHA_TECNICA B
    ON A.COD_MAT_PROD=B.COD_MAT_PROD
        AND A.COD_EMPRESA=B.COD_EMPRESA 
    LEFT JOIN ESTOQUE C
    ON B.COD_MAT_NECES=C.COD_MAT
        AND A.COD_EMPRESA=C.COD_EMPRESA
    INNER JOIN MATERIAL D
    ON B.COD_MAT_NECES=D.COD_MAT
        AND A.COD_EMPRESA=D.COD_EMPRESA
    WHERE (A.QTD_PLAN-A.QTD_PROD)<>0
        AND A.COD_EMPRESA=1
        AND A.ID_ORDEM=3;


--PARAMETROS (P_EMP - P_ID_ORDEM -P_COD_MAT_PROD - P_QTD_APON - P_LOTE_PROD)
SET SERVEROUTPUT ON
EXECUTE PROC_APONTAMENTO (1,3,1,5,'QWE');

SELECT * FROM NOTA_FISCAL;

--PARAMENTROS (P_EMP IN NUMBER, P_NUM_NF NUMBER, P_DATA_MOVT
SET SERVEROUTPUT ON
EXECUTE PROC_INTEGR_NF_ESTOQUE (1,16,'15/01/2026');
EXECUTE PROC_INTEGR_NF_ESTOQUE (1,17,'15/01/2026');
EXECUTE PROC_INTEGR_NF_ESTOQUE (1,18,'15/01/2026');

--SELECT * FROM ESTOQUE
--SELECT * FROM ESTOQUE_LOTE

--SELECT * FROM ORDEM_PROD

--SELECT * FROM ORDEM_PROD
--EXEC PROC_APONTAMENTO 1,1,10,TESTE1
