--===========================================
-- TRIGGER PARA AUDITAR ALTERACOES DE SALARIO
--===========================================

-- ATIVA SOMENTE SE HOUVER MUDANCAS NO ATRIBUTO 'SALARIO.SALARIO'
CREATE OR REPLACE TRIGGER TRG_AUDIT_SAL
AFTER INSERT OR UPDATE OF SALARIO ON SALARIO 
  FOR EACH ROW

BEGIN
    IF inserting THEN 
        INSERT INTO AUDITORIA_SALARIO VALUES 
        (:NEW.COD_EMPRESA,:NEW.MATRICULA,0,:NEW.SALARIO,USER,SYSDATE);
    ELSIF updating THEN 
        INSERT INTO AUDITORIA_SALARIO VALUES 
        (:NEW.COD_EMPRESA,:NEW.MATRICULA,:OLD.SALARIO,:NEW.SALARIO,USER,SYSDATE);
    END IF;
END;


--=========================
-- TESTES
-- ========================

SELECT * FROM AUDITORIA_SALARIO;

--SIMULAÇÃO DE ALTERAÇÃO SALARIAL PARA ATIVAÇÃO DA TRIGGER DE AUDITORIA
UPDATE SALARIO SET SALARIO=SALARIO*1.05
WHERE COD_EMPRESA=1
AND MATRICULA=8;
COMMIT;